[package]
name = "rust-rendering-2d"
version = "0.1.0"
edition = "2021"

[dependencies]
miniquad = "0.3.15"
sdl2 = { version = "0.35.2", features = ["image", "ttf"] }
serde = { version = "1.0.152", features = ["derive"] }
serde-wasm-bindgen = "0.5.0"
rhai = "1.12.0"
